version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: chatapp2024

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: chatapp2024
      ME_CONFIG_MONGODB_URL: mongodb://root:chatapp2024@localhost:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis 
    ports:
      - 6379:6379

  redis-stack:
    image: redis/redis-stack
    ports:
      - 8001:8001   
  
  zookeeper:
    image: zookeeper
    ports: 
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.8.41:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.8.41:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
